using Microsoft.Xna.Framework;
using REB.Engine.ECS;

namespace REB.Engine.Combat;

/// <summary>
/// Snapshot of a single damage event generated by <see cref="Systems.CombatSystem"/>.
/// Consumed by downstream systems (audio, animation, loot) within the same frame.
/// </summary>
public readonly struct CombatEvent
{
    /// <summary>Entity that dealt the damage.</summary>
    public readonly Entity Attacker;

    /// <summary>Entity that received the damage.</summary>
    public readonly Entity Target;

    /// <summary>Raw damage amount applied this hit.</summary>
    public readonly float Damage;

    /// <summary>World-space midpoint between attacker and target at impact.</summary>
    public readonly Vector3 HitPoint;

    /// <summary>Normalised direction from attacker toward target (used for knockback).</summary>
    public readonly Vector3 KnockbackDirection;

    public CombatEvent(
        Entity attacker, Entity target,
        float damage, Vector3 hitPoint, Vector3 knockbackDirection)
    {
        Attacker           = attacker;
        Target             = target;
        Damage             = damage;
        HitPoint           = hitPoint;
        KnockbackDirection = knockbackDirection;
    }
}
