using Microsoft.Xna.Framework;
using REB.Engine.ECS;

namespace REB.Engine.Physics;

/// <summary>
/// Describes a single collision contact generated by <see cref="Systems.PhysicsSystem"/>
/// during one frame. Consuming systems (combat, triggers, audio, etc.) read these
/// from <see cref="Systems.PhysicsSystem.CollisionEvents"/> each frame.
/// </summary>
public readonly struct CollisionEvent
{
    /// <summary>First entity in the collision pair.</summary>
    public readonly Entity EntityA;

    /// <summary>Second entity in the collision pair.</summary>
    public readonly Entity EntityB;

    /// <summary>World-space collision normal, pointing from B toward A.</summary>
    public readonly Vector3 Normal;

    /// <summary>Penetration depth along the normal axis (world units).</summary>
    public readonly float Depth;

    /// <summary>
    /// True when at least one party is a trigger volume.
    /// Triggers receive events but no physics response is applied.
    /// </summary>
    public readonly bool IsTrigger;

    public CollisionEvent(Entity a, Entity b, Vector3 normal, float depth, bool isTrigger)
    {
        EntityA   = a;
        EntityB   = b;
        Normal    = normal;
        Depth     = depth;
        IsTrigger = isTrigger;
    }
}
