namespace REB.Engine.UI;

/// <summary>
/// Classifies game-feel feedback events generated by <see cref="Systems.HitFeedbackSystem"/>.
/// Drives screen-shake intensity, particle bursts, and gamepad rumble patterns.
/// </summary>
public enum FeedbackType
{
    None,
    HitEnemy,
    HitPlayer,
    HitPrincess,
    BossDefeated,
    PrincessDropped,
    GoldCollected,
    UpgradePurchased,
}
